### ISSUE TITLE
"team already exists" error appear on bungeecoord when using Laser

### ISSUE THREAD

**Issue by Pitrex** [SkytAsul/GuardianBeam#1]
As said bungeecoord kick all players with message team already exists when using Laser.
Actuall first laser works correctly and only the second time I use it it breaks.
The solution of changing "noclip" to something else doesn't work as now the error says that team doesn't exists and gives new name given by me. Also now first time the laser works invisible mob pusheh player around.

**Comment by SkytAsul** [comment]
Fixed.

**Comment by ghost** [comment]
Issue doesn’t seem to be fixed, just received a report from someone using my plugin that this exact same thing happened, commenting out code related to teams however seemed to fix it, so not sure on what the teams are even used for.

**Comment by SkytAsul** [comment]
Are you using Laser version 2.0?

**Comment by ghost** [comment]
> Are you using Laser version 2.0?

My plugin implements it, yes

**Comment by ghost** [comment]
![logs](https://user-images.githubusercontent.com/54047826/131157056-519ecf5e-67c4-41ea-9e81-9cc0f0823325.png)

**Comment by SkytAsul** [comment]
That's pretty weird, doesn't this happen only when the laser gets hidden and shown again to a player?

**Comment by ghost** [comment]
> That's pretty weird, doesn't this happen only when the laser gets hidden and shown again to a player?

From what I understand, yes.

**Comment by SkytAsul** [comment]
Please try with version 2.0.1.

**Comment by SkytAsul** [comment]
Please reopen if it still happens.
