### ISSUE TITLE
Problem after the beam has timed out - solution

### ISSUE THREAD

**Issue by Goldentoenail** [SkytAsul/GuardianBeam#13]
Based on your LaserDemo, I created a plugin idea which uses fixed locations for the start and end locations.
The problem I had was that when I used a fixed duration, the 'synchronized void cancel()' did not work!
Leaving the 'lasers.remove(p);' in this function, as not being applied.
I kept getting 'null' errors because the laser existed, but the runnable did not. (When repeating the (toggle) command).

I eventually discovered that instead of using the standard code
`this.laser = new CrystalLaser(originLocation, endLocation, 5, 50);`
I could use the extended code
`this.laser = new CrystalLaser(originLocation, endLocation, 5, 50).executeEnd(() -> Bukkit.broadcastMessage("Laser ended!")).start(plugin);`
But, NOT in this format! (NO .start(plugin)
To get around my problem I used
`this.laser = (CrystalLaser) new CrystalLaser(originLocation, endLocation, 5, 50).executeEnd(() -> lasers.remove(p));`

Perhaps you could adujst the plugin to accomodate something like this.
Or, add this solution to the Wiki guide?

**Comment by SkytAsul** [comment]
I cannot understand your problem. Can you post more code? What is this "lasers" object? What are you trying to achieve?
