### ISSUE TITLE
New laser type: particles

### ISSUE THREAD

**Issue by Doc94** [SkytAsul/GuardianBeam#18]
Well not sure if the warden works like the others beam, if so can be good have this added to?

**Comment by SkytAsul** [comment]
It's not the same type of laser. It is simply a beam of particles. Though I could add a new laser type simply made of particles.

**Comment by Doc94** [comment]
> It's not the same type of laser. It is simply a beam of particles. Though I could add a new laser type simply made of particles.

okay i has this question if that beam was a entity or full particles.. then yeah looks better a support for particles, thanks.

**Comment by chrisgdt** [comment]
> okay i has this question if that beam was a entity or full particles.. then yeah looks better a support for particles, thanks.

You can have a look to XSeries and their XParticles, with a lot a utilitaries functions with particles.
https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/particles/XParticle.java

**Comment by SkytAsul** [comment]
After some thought, it would be a pain due to the complex nature of spawning particles (particle data, different particle types among versions...).
You can use XParticles to do a beam of particles as the user above pointed out!
