### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by WastProd** [SkytAsul/GuardianBeam#20]
Hey ! it would be cool if this lib support 1.19.4 :D

**Comment by SkytAsul** [comment]
It already has 1.19.4 support (commit from 3 weeks ago: https://github.com/SkytAsul/GuardianBeam/commit/3627bc7e25317285d73af28a4021c950e7a0453c)

**Comment by WastProd** [comment]
Sorry i miss it !! And huge thx btw !
