### ISSUE TITLE
Kicked & error when targeting crystal laser over a certain amount of time

### ISSUE THREAD

**Issue by Nesanco** [SkytAsul/GuardianBeam#22]
Guardian Beam Version - 2.3.5
Server Version - Paper 1.20
Error - https://pastebin.com/ijJWpW1d
Code - https://pastebin.com/u9z2qiXh

If you want to reproduce exactly:

1. Download [Server files](https://drive.google.com/file/d/1SvgQYfpZhnufWJclKyC7ZvAlqSs4M4oW/view?usp=sharing)
2. Use /beam create test
3. Move a few blocks away and do /beam target test 1 (Error will not occur)
4. Do /beam target test 100 (Error will occur)

**Comment by SkytAsul** [comment]
Can you try again with file from latest commit?

**Comment by Nesanco** [comment]
I dont get kicked anymore but now if I target the beam over 100 ticks for example, it goes to a completely random location, not my location, same setup as above but with the new version 

[Video](https://medal.tv/games/minecraft/clips/1IElIEypMIus1A/d1337ZcwDAbh?invite=cr-MSxFQk4sOTA4NTY3MTIs)

**Comment by SkytAsul** [comment]
May you try with latest commit again?

**Comment by Nesanco** [comment]
seems to be working now, thanks

**Comment by SkytAsul** [comment]
Perfect :ok_hand: thanks for the detailed explanations on how to reproduce!
