### ISSUE TITLE
1.20.6/1.21

### ISSUE THREAD

**Issue by Ekpoa** [SkytAsul/GuardianBeam#26]
Is there plans to update this api to 1.20.6 and 1.21??

**Comment by SkytAsul** [comment]
There are plans but no time

**Comment by Ekpoa** [comment]
its all good, i made my own :D

**Comment by SkytAsul** [comment]
Would you be kind enough to make a PR? :)

**Comment by Ekpoa** [comment]
i rewrote it entirely and its multi module. so cant really pr it :D and its only basic beam. 
https://github.com/Ekpoa/PoaSkRewritev2

the code is written for each version 1.20.2+
sorry

**Comment by SkytAsul** [comment]
I see, too bad!

For the other devs checking this issue: I'll eventually add the 1.20.5/1.21 support, don't worry.

**Comment by cabbagegod** [comment]
> I see, too bad!
> 
> For the other devs checking this issue: I'll eventually add the 1.20.5/1.21 support, don't worry.

Any progress on this? Would love to use this on the latest!

**Comment by SkytAsul** [comment]
I completely forgot about this. I started working on the update but many things changed so it may take a bit of time, but I hope it will be over during the week.

**Comment by cabbagegod** [comment]
> I completely forgot about this. I started working on the update but many things changed so it may take a bit of time, but I hope it will be over during the week.

Oh sweet! That would be amazing. I have so many cool things I could make with this.

**Comment by SkytAsul** [comment]
This is complete with 2.4.0 :)
