### ISSUE TITLE
Laser stop moving after first move

### ISSUE THREAD

**Issue by iBuseWinner** [SkytAsul/GuardianBeam#4]
Hey.

I tried to make something like gobo, but when I firstly move laser's end it reach end location but isn't moving to another end location...

**Comment by iBuseWinner** [comment]
laser1 and laser2 moving to move1 and move2, but don't moving to beam1End and beam2End and stopping.

![image](https://user-images.githubusercontent.com/44753872/128858825-f9a2cea8-4fe2-4883-86a0-ec3753ac37ad.png)

**Comment by SkytAsul** [comment]
You probably have to use `Bukkit.getScheduler.runTask(plugin, () -> laser1.moveEnd(beam1End, 40, laser1::stop));` as the callback is ran when the move is not really _terminated_, the laser is not able to start another move until the end of the tick.

**Comment by iBuseWinner** [comment]
> You probably have to use `Bukkit.getScheduler.runTask(plugin, () -> laser1.moveEnd(beam1End, 40, laser1::stop));` as the callback is ran when the move is not really _terminated_, the laser is not able to start another move until the end of the tick.

I changed my code to this:

![image](https://user-images.githubusercontent.com/44753872/129416028-a4734529-be6e-48d7-be62-ffdaa1671a50.png)

But if I'll try to launch this code second or more time, then lasers will spawn from laser.starter to laser.end not laser.start...

They should be going up, but in fact they are going down

![image](https://user-images.githubusercontent.com/44753872/129416110-ae360783-d197-4fdf-8def-875e4a71dea3.png)

**Comment by SkytAsul** [comment]
In Laser#moveEnd or Laser#moveStart, use Location#clone as it will mutate the location.

**Comment by iBuseWinner** [comment]
> In Laser#moveEnd or Laser#moveStart, use Location#clone as it will mutate the location.

Thank you!
Now lasers moving dancing
