### ISSUE TITLE
Lasers can not be re-started after being stopped for the first time.

### ISSUE THREAD

**Issue by ghost** [SkytAsul/GuardianBeam#5]
This bug has caused me very much headache as I need to constantly create new GuardianLaser instances every time I want a laser to turn back on from being stopped. Example code is below. In very rapid succession of stops and starts, this causes a very bad race condition for me **EVEN AFTER USING A ReentrantLock AND the synchronized keyword!**

`import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

public class TestCommand implements CommandExecutor {
    Laser.GuardianLaser lsr;
    
    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if(sender instanceof Player) {
            if (args[0].equals("new")) {
                try {
                    lsr = new Laser.GuardianLaser(((Player) sender).getLocation(),((Player) sender).getLocation().add(0,5,0),-1,128);
                } catch (ReflectiveOperationException e) {
                    e.printStackTrace();
                }
            } else if (args[0].equals("on")) {
                if(!lsr.isStarted()) lsr.start(// ADD PLUGIN HERE!);
            } else if (args[0].equals("off")) {
                if (lsr.isStarted()) lsr.stop();
            }
            return true;
        }
        return false;
    }
}`
You can try this out for yourself by doing /test new, /test on, /test off, /test on. Nothing happens after the laser is turned off for the first time. This bug also affects the CrystalLasers.

Environment: 1.17.1, java 16, PaperMC server, no other related plugins that could cause issues. Latest 2.0.0 version of this resource.

**Comment by ghost** [comment]
Just tested, also affects CrystalLasers as I thought.

**Comment by chrisgdt** [comment]
Fixed in #6 !
