### ISSUE TITLE
Laser endpoints extend out slightly farther than they should

### ISSUE THREAD

**Issue by ghost** [SkytAsul/GuardianBeam#7]
![2021-09-01_01 40 43](https://user-images.githubusercontent.com/54047826/131585005-a3dedc9b-cd65-4eb2-a935-1b5f8b9d6c9a.png)
In the screenshot, you can see the end point of a laser sticking out farther than it should, since in code the location the beam is pointing at is at the exact intersection between these two beams. (One has their starting point at the intersection, one has their end point)
![2021-09-01_01 42 46](https://user-images.githubusercontent.com/54047826/131585132-a7c5f3a4-7d82-416c-9acf-17a8c67f818a.png)
In this screenshot you see the same issue, all these beams have their end points pointing at the exact same location (I have verified this!) yet they extend out slightly farther than they should.

**Comment by SkytAsul** [comment]
I am finally fixing this!
![image](https://user-images.githubusercontent.com/28827134/156942410-c6032cb3-11f5-48c4-bbfa-28d2b080b7f2.png)
