### ISSUE TITLE
Feature request: Compatible with 1.18

### ISSUE THREAD

**Issue by YannisHofmann** [SkytAsul/GuardianBeam#9]
Hey,
I would really love to use this util in the new 1.18 version. 
Do you have any plans to make this compatible with the latest version?

**Comment by Laurenshup** [comment]
Before posting. Next time read our announcements in the Discord. As mentioned there, has been coded, only waiting for publication, some time this week.

**Comment by SkytAsul** [comment]
Updated a few days ago.

**Comment by YannisHofmann** [comment]
Thank You
